### ISSUE TITLE
Review documentation and deliver To-Do list follow along tutorial

### ISSUE THREAD

**Issue by CallmeT-ty** [powerhouse-inc/powerhouse#256]
Goal: Take an external developer through the logic and methods required for creating a document model. We are aiming to do this with a follow along tutorial for a To-Do list that has a counter with the 'checked' & 'pending' to-do list items. 

The current documentation is divided up in 3 parts.
Pt 1: Document model generation (to be reviewed by @acaldas)
Pt 2: Reducers (to be reviewed by @ryanwolhuter)
Pt 3: Editors (to be reviewed by @gpuente)

I'd like to tackle the documentation in iterative steps with the following tasks 

- [ ] Come up & create a prototype of a very simple document model that drives a simple editor for a to do list table with calculator that counts the checked & pending to-do-list items. 
- [ ] Each team member to review the current documentation and correct it where necessary.
- [ ] Add more tips, hints and crucial knowledge that the developer would need to become familiar with document modelling
- [ ] Add the code and guidance for creating the to-do list in a follow along tutorial.

The following link allows to get access to the gitbook as an editor. https://app.gitbook.com/invite/FPp65d2JPvIsnzMJUUcp/Ybx3plW0ZstoFq3keSnH
