### ISSUE TITLE
Update composition settings after Ecosystem API is ready

### ISSUE THREAD

**Issue by valiafetisov** [powerhouse-inc/powerhouse#353]
### Goal
Ecosystem API is composed together with the rest of the queries

### Context
After implementation of the [migration strategy](https://github.com/powerhouse-inc/switchboard-boilerplate/issues/60), we're waiting for the [makerdao-ses/ecosystem-api](https://github.com/makerdao-ses/ecosystem-api) to be changed according to the proposal. After that, we should redeploy the same codebase with a new env variable `ECOSYSTEM_GQL_ENDPOINT` to be set to `https://ecosystem-dashboard.herokuapp.com/graphql`.

### Tasks
- [x] Clearly outline required changes
- [x] Notify relevant stakeholders
- [ ] Check that changes has been applied
- [ ] Change `ECOSYSTEM_GQL_ENDPOINT` env var
- [ ] Re-trigger the deployment
- [ ] Validate that the endpoints are properly composed together
