### ISSUE TITLE
Setup deployment pipelines

### ISSUE THREAD

**Issue by valiafetisov** [powerhouse-inc/powerhouse#354]
### Goal
Production deployment running on the powerhouse infrastructure

### Context
Currently, we have staging deployment to our own cluster with configuration files living in external repo, which is not even automatically triggered due to the security restrictions (see reasoning in https://github.com/powerhouse-inc/switchboard-boilerplate/pull/56#discussion_r1237029390). After this issue is done, we want to add (and later replace it) multiple new deployment pipelines running on the powerhouse infrastructure:

- deploy `dev` branch automatically
- deploy `staging` branch automatically
- deploy `main` branch via a trigger (I suppose something like `release` or [`workflow_dispatch`](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch)) would work

For this we will need to eventually agree on:
- the service/cluster where it will be deployed (please propose one or multiple options)
- the domain name for each environment (please propose)
- trigger for the `main` branch deployment (please propose one or multiple options)
- the CI infrastructure (please propose one or multiple options)
- if dev/staging need to be additionally protected (eg by github auth and if this is possible)
- shared secret management (if any)

Note: we should optimize for the simplicity of the setup and operation (so it's not a private kubernetes setup with multiple UIs that also need to be managed by devops engineer) but rather something small and managed, like Vercel (that powerhouse team seems to be using already). Unless they decide to have more flexibility/independence 🙂 

### Tasks
- [ ] Outline the proposal(s)
- [ ] Outline requirements/actions that needs to be taken from the powerhouse side
- [ ] Setup new deployment pipelines according to the proposal
