### ISSUE TITLE
Integrate `document-model-libs`

### ISSUE THREAD

**Issue by valiafetisov** [powerhouse-inc/powerhouse#355]
### Goal
Graphql API serving endpoints based on the `document-model-libs` schema

### Context
Switchboard API (this repository) have to eventually behave based on the business logic developed in the other repository [makerdao-ses/document-model-libs](https://github.com/makerdao-ses/document-model-libs) and infer as much structure from the schema defined there, as possible. To better understand proposed integration, SES team prepared its PoC assembled in another repository [acaldas/ql-boilerplate](https://github.com/acaldas/ql-boilerplate). The purpose of this issue is to better align on the chosen integration structure

### Tasks
- [x] Publish analysis of the provided PoC
- [x] Propose the way forward
- [ ] Get external confirmation
