### ISSUE TITLE
Agree on auth, roles and permissions

### ISSUE THREAD

**Issue by valiafetisov** [powerhouse-inc/powerhouse#358]
### Goal
Agree on the overall functionality related to auth

### Context
Since the initial version of the authentication was already implemented in powerhouse-inc/switchboard#16 and powerhouse-inc/switchboard#28, it's time to make it production-ready and close all open questions.

### Tasks
- [x] Prepare open questions
- [x] Propose an answer to each question
- [x] Ask for feedback
- [ ] Conclude by writing next steps
