### ISSUE TITLE
SwitchboardAPI: Milestone

### ISSUE THREAD

**Issue by LukSteib** [powerhouse-inc/powerhouse#359]
## Milestone Scope Overview

Based on the https://github.com/makerdao-ses/switchboard-boilerplate/issues/3#issuecomment-1437098636

### Scope: Milestone 1
- [x] Finalise document model requirement ([see here](https://github.com/makerdao-ses/switchboard-boilerplate/issues/1))
- [x] Setup a project with a linter and a prettier
- [x] Setup ORM, declarative module structure
- [x] Setup tests for operations, models, database integration
- [x] Add CI steps to enforce tests, coverage, correct build outcome
- [x] Setup API playground (+possibly make database/code comments visible in the playground)
- [x] Add input validator (+possibly enforce its use via the config structure)
- [x] Implement authentication as a plugin/middleware
- [x] Enforce high code coverage
- [x] Setup advanced logging library like [winston](https://github.com/winstonjs/winston), enforce correct usage (via a readme guide, linter settings)
- [ ] Setup something like [tsdoc](https://tsdoc.org/) (can be enforced via a linter rule)
- [ ] Setup database migrations
- [ ] Implement UI to login, create users and their API keys
- [ ] Implement authorization on per action bases
- [ ] Add CD steps to build and deploy staging on merge to main
- [ ] Store history of every record
- [ ] Store change requests (endpoint path, parsed request body, reference to the record version it produced)
- [ ] Store attached files (as base64 or upload them somewhere)
- [ ] Implement existing modules
