### ISSUE TITLE
When i create a new SPV or Asset i get kicked out of the asset creation modal

### ISSUE THREAD

**Issue by CallmeT-ty** [powerhouse-inc/powerhouse#38]
![Image](https://github.com/user-attachments/assets/804eab2b-b20f-4871-9b3c-5db8ad30936b)

**Additional UI updates** 

- [x] powerhouse-inc/powerhouse#37 
- [x] powerhouse-inc/powerhouse#36 
- [x] powerhouse-inc/powerhouse#35 
- [x] powerhouse-inc/powerhouse#34

**Comment by CallmeT-ty** [comment]
Present on Dev environment. But we'll need to deploy to maker staging and further environments.
